In [2]:
import numpy as np

In [18]:
a = np.array([1,2,3,4.5,5])
b = np.array([3,4,5,6.1,1],dtype='int32')

In [16]:
for i in b:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [19]:
np.ones(10)*8

array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

In [20]:
np.zeros(4)*6

array([0., 0., 0., 0.])

In [26]:
arr = np.ones(10,dtype='int32')*8

In [29]:
print(type(arr))


<class 'numpy.ndarray'>


In [30]:
np.full(10,11)

array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11])

In [31]:
np.array([(1,2,3),(4,5,6)])

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
ar = np.arange(0,4.1,0.8)

In [35]:
for i in ar:
    print(i) 

0.0
0.8
1.6
2.4000000000000004
3.2
4.0


In [45]:
ele = np.random.normal(0,1,(1,8))

In [49]:
ele

array([[-0.81584402, -1.79761415, -0.6288849 , -0.46032022, -0.65949088,
        -0.70656296, -1.33120808,  1.47791149]])

In [54]:
cem  = 0

In [42]:
cem

array([-1.07169067, -0.38150353,  0.524936  ,  0.54468806, -0.95933563,
       -0.87930919, -2.311381  ,  0.49565914])

In [55]:
b = np.random.randint(1,20,(4,3))

In [56]:
b

array([[15,  7,  3],
       [10,  4, 12],
       [ 1, 13, 18],
       [18,  2,  5]])

In [71]:
b = np.random.randint(1,40,(5,2,2))

In [72]:
b

array([[[ 9, 11],
        [16, 28]],

       [[10, 17],
        [39, 13]],

       [[28, 23],
        [11, 12]],

       [[ 6,  5],
        [ 6, 18]],

       [[11, 28],
        [26, 35]]])

In [59]:
b.ndim

3

In [60]:
b.shape

(2, 4, 4)

In [61]:
b.size

32

In [62]:
c = np.arange(1,10)

In [63]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
c.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [65]:
x = np.array((4,5,6))
x.ndim

1

In [66]:
y = x.reshape(3,1)

In [67]:
y

array([[4],
       [5],
       [6]])

In [73]:
y.ndim

2

In [80]:
i = np.array(([1,2,3],[4,5,6]))
l =np.array(([7,8,9]))

In [81]:
np.vstack([i,l])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
aray = np.random.randint(1,30,16)
a

array([1. , 2. , 3. , 4.5, 5. ])

In [83]:
aray

array([19, 29, 13, 19, 20, 28, 25, 26, 20, 10, 18,  1,  1,  9,  9, 23])

In [84]:
aray2 = np.split(aray,[3,8])

In [85]:
aray2

[array([19, 29, 13]),
 array([19, 20, 28, 25, 26]),
 array([20, 10, 18,  1,  1,  9,  9, 23])]

In [87]:
arr1 = np.random.randint(0,20,9).reshape(3,3)

In [88]:
arr1

array([[ 4, 16,  9],
       [14, 14,  8],
       [13,  8, 14]])

In [91]:
arr2 = np.split(arr1,[1,2])

In [94]:
np.array(arr2)

array([[[ 4, 16,  9]],

       [[14, 14,  8]],

       [[13,  8, 14]]])

In [96]:
arr3 = np.argsort(arr2)

In [97]:
arr3

array([[[0, 2, 1]],

       [[2, 0, 1]],

       [[1, 0, 2]]], dtype=int64)

In [122]:
f = np.random.randint(1,40,9)

In [123]:
f

array([36, 12, 16, 15, 30, 36,  5,  9, 30])

In [126]:
f

array([36, 12, 16, 15, 30, 36,  5,  9, 30])

In [124]:
np.argmax(f)

0

In [127]:
np.argmin(f)

6

In [128]:
sum(f)

189

In [129]:
liste = np.arange(1,7)

In [130]:
liste

array([1, 2, 3, 4, 5, 6])

In [134]:
liste = np.ones(6) 

In [139]:
liste = np.zeros([3,4])

In [140]:
liste

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [143]:
liste =  np.ones([4,5]) * 8

In [145]:
liste = np.arange(20,50,3)

In [146]:
liste

array([20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [147]:
liste = np.linspace(0,20,5)

In [148]:
liste

array([ 0.,  5., 10., 15., 20.])

In [158]:
liste = np.random.randn(12).reshape(3,4)

In [159]:
liste

array([[-0.08568336, -0.63740771, -0.12187511, -1.66219925],
       [-1.85877673,  1.07519954, -0.22442595, -0.1409925 ],
       [ 0.05068398,  0.1245151 ,  0.00791481, -1.21382516]])

In [160]:
liste = np.random.randint(1,30,20).reshape(5,4)

In [161]:
liste

array([[12, 15, 26, 28],
       [20, 20,  6,  7],
       [26, 26,  8, 29],
       [17, 19, 26,  5],
       [27, 14,  6,  5]])

In [162]:
liste[0,:]

array([12, 15, 26, 28])